/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2017-08-14 07:38:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>内容管理系统</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"jslib/jquery-easyui-1.5.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"jslib/jquery-easyui-1.5.2/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"jslib/jquery-easyui-1.5.2/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"jslib/jquery-easyui-1.5.2/themes/default/easyui.css\"\r\n");
      out.write("\ttype=\"text/css\"></link>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"jslib/jquery-easyui-1.5.2/themes/icon.css\"\r\n");
      out.write("\ttype=\"text/css\"></link>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div data-options=\"region:'north',border:false\"\r\n");
      out.write("\t\tstyle=\"height: 60px; background: #B3DFDA; padding: 10px\">来个主题图片\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'west',split:true,title:'新闻公告'\"\r\n");
      out.write("\t\tstyle=\"width: 450px; padding: 10px;\">west content</div>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tdata-options=\"region:'east',split:true,collapsed:false,title:'天气/日历/有情链接'\"\r\n");
      out.write("\t\tstyle=\"width: 300px; padding: 10px;\">\r\n");
      out.write("\t\t<iframe name=\"sinaWeatherTool\"\r\n");
      out.write("\t\t\tsrc=\"http://weather.news.sina.com.cn/chajian/iframe/weatherStyle40.html?city=%E5%B7%B4%E5%BD%A6%E6%B7%96%E5%B0%94\"\r\n");
      out.write("\t\t\twidth=\"260\" height=\"113\" marginwidth=\"0\" marginheight=\"0\" hspace=\"0\"\r\n");
      out.write("\t\t\tvspace=\"0\" frameborder=\"0\" scrolling=\"no\"> </iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"margin: 10px 0\"></div>\r\n");
      out.write("\t\t<div class=\"easyui-calendar\" style=\"width: 260px; height: 250px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"margin: 10px 0\"></div>\r\n");
      out.write("\t\t<div class=\"easyui-panel\" title=\"有情链接\"\r\n");
      out.write("\t\t\tstyle=\"width: 260px; height: 430px; background: #fafafa;\"\r\n");
      out.write("\t\t\tdata-options=\"iconCls:'icon-save',closable:false,\r\n");
      out.write("    \t\t\t\t\t  collapsible:true,minimizable:false,maximizable:false\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://www.w3school.com.cn\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-decoration: none;\">W3School</a></li>\r\n");
      out.write("\t\t\t\t<div style=\"margin: 10px 0\"></div>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://www.baidu.com\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-decoration: none;\">百度知道</a></li>\r\n");
      out.write("\t\t\t\t<div style=\"margin: 10px 0\"></div>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://www.vsupa.com/\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-decoration: none;\">云算盘智能财税平台</a></li>\r\n");
      out.write("\t\t\t\t<div style=\"margin: 10px 0\"></div>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://www.jeasyui.net/\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-decoration: none;\">Jquery EasyUI中文网</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div data-options=\"region:'center',title:'CMS系统登录'\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tdata-options=\" region:'east',split:true,style:{position:'absolute',right:50,top:150}\"\r\n");
      out.write("\t\t\tclass=\"easyui-panel \" title=\"用户登录\"\r\n");
      out.write("\t\t\tstyle=\"width: 300px; text-align: center;\">\r\n");
      out.write("\t\t\t<div style=\"padding: 10px 60px 20px 60px\">\r\n");
      out.write("\t\t\t\t<form id=\"login_form\" class=\"easyui-form\" method=\"post\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"novalidate:true\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"5\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"userId\" name=\"id\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-textbox\" type=\"text\" name=\"userCode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalidType=\"complexValid['^[0-9a-zA-Z]+$','编码只能包含字母、数字','/userCode/ajax','userCode','用户编码已被占用,换一个试试!','userId']\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'账号'\" iconCls=\"icon-man\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticonAlign=left style=\"width: 100%; height: 32px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-textbox\" required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'账号',validType:'length[6,20]'\" iconCls=\"icon-man\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticonAlign=left style=\"width: 100%; height: 32px\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-textbox\" type=\"password\" required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"prompt:'密码',validType:'length[6,20]'\"\r\n");
      out.write("\t\t\t\t\t\t\t\ticonCls=\"icon-lock\" iconAlign=left\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%; height: 32px\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <td><input id=\"inputCheckCode\" class=\"easyui-textbox\" required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'验证码',validType:'validValidCode'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticonCls=\"icon-filter\" iconAlign=left\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 55%; height: 32px\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"validImg\" src=\"/cms/user/getValidNum.do\" alt=\"\" width=\"56\" height=\"32\" align='absMiddle' />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id = \"validCodeInSession\" >\r\n");
      out.write("\t\t\t\t\t\t\t   </a>\r\n");
      out.write("\t\t\t\t\t\t\t</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"validCodeInSession\" name=\"validCodeInSession\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-textbox\" type=\"text\" name=\"inputValidCode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalidType=\"validValidCode['^[0-9a-zA-Z]{4,4}$','验证码为4位字母、数字','user/checkValidCode.do','inputValidCode','验证码输入不正确!','validCodeInSession']\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"prompt:'验证码'\" iconCls=\"icon-filter\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticonAlign=left style=\"width: 55%; height: 32px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img id=\"validImg\" src=\"/cms/user/getValidNum.do\" alt=\"\" width=\"56\" height=\"32\" align='absMiddle' />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center; padding: 5px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" rel=\"external nofollow\" rel=\"external nofollow\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-linkbutton\" style=\"width: 45%; height: 32px\" onclick=\"submitLoginForm()\">登录</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" rel=\"external nofollow\" rel=\"external nofollow\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-linkbutton\" style=\"width: 45%; height: 32px\">注册</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div data-options=\"region:'south',border:false\"\r\n");
      out.write("\t\tstyle=\"height: 50px; background: #A9FACD; padding: 10px; text-align: center;\">\r\n");
      out.write("\t\t版权所有 © 2017 主办：DLY 苏ICP备0478号 技术支持：简爱公司</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//点击更换验证码  \r\n");
      out.write("$('#validImg').click(function() {  \r\n");
      out.write("\tvar timestamp = new Date().getTime();\r\n");
      out.write("    $(this).attr(\"src\", '/cms/user/getValidNum.do?'+ timestamp);\r\n");
      out.write("});  \r\n");
      out.write("\r\n");
      out.write("// 校验验证码\r\n");
      out.write("$.extend($.fn.validatebox.defaults.rules, {\r\n");
      out.write("\t// 混合验证，五个参数：第一个是正则表达式，第二个是错误提示信息，前两个参数用户合法性验证；第三个是调用的url，第四个是传递给服务器的参数名(参数key)，第五个是错误提示信息，第六个参数是当前表单id字段\r\n");
      out.write("    validValidCode: {\r\n");
      out.write("    \tvalidator: function(value, param) {\r\n");
      out.write("            var m_reg = new RegExp(param[0]);\r\n");
      out.write("            if (!m_reg.test(value)) {\r\n");
      out.write("            \tconsole.log('0');\r\n");
      out.write("                $.fn.validatebox.defaults.rules.validValidCode.message = param[1];//动态设置message提示信息，validValidCode与方法名对应\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("            \tconsole.log('1');\r\n");
      out.write("                var postdata = {};\r\n");
      out.write("                postdata[param[3]] = value;  //动态的key和value对应\r\n");
      out.write("                //postdata['id'] = $(\"#\"+param[5]).val();//获取id值\r\n");
      out.write("                var result = $.ajax({\r\n");
      out.write("                    url: param[2],  //动态URL\r\n");
      out.write("                    data: postdata,\r\n");
      out.write("                    async:false,\r\n");
      out.write("                    type: \"post\"\r\n");
      out.write("                }).responseText;\r\n");
      out.write("                if (result === \"Error\") {\r\n");
      out.write("                    $.fn.validatebox.defaults.rules.validValidCode.message = param[4];  //动态设置message提示信息，validValidCode与方法名对应\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                else {\r\n");
      out.write("                    return true;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("\tmessage : \"\"\r\n");
      out.write("    }       \r\n");
      out.write("});  \r\n");
      out.write("\r\n");
      out.write("$.extend($.fn.validatebox.defaults.rules, {\r\n");
      out.write("    // 混合验证，五个参数：第一个是正则表达式，第二个是错误提示信息，前两个参数用户合法性验证；第三个是调用的url，第四个是传递给服务器的参数名(参数key)，第五个是错误提示信息，第六个参数是当前表单id字段\r\n");
      out.write("    complexValid : {\r\n");
      out.write("       validator: function(value, param) {\r\n");
      out.write("           var m_reg = new RegExp(param[0]);\r\n");
      out.write("           if (!m_reg.test(value)) {\r\n");
      out.write("               $.fn.validatebox.defaults.rules.complexValid.message = param[1];//动态设置message提示信息，complexValid与方法名对应\r\n");
      out.write("               return false;\r\n");
      out.write("           }\r\n");
      out.write("           else {\r\n");
      out.write("               var postdata = {};\r\n");
      out.write("               postdata[param[3]] = value;  //动态的key和value对应\r\n");
      out.write("               postdata['id'] = $(\"#\"+param[5]).val();//获取id值\r\n");
      out.write("               var result = $.ajax({\r\n");
      out.write("                   url: param[2],  //动态URL\r\n");
      out.write("                   data: postdata,\r\n");
      out.write("                   async:false,\r\n");
      out.write("                   type: \"post\"\r\n");
      out.write("               }).responseText;\r\n");
      out.write("               if (result == \"false\") {\r\n");
      out.write("                   $.fn.validatebox.defaults.rules.complexValid.message = param[4];  //动态设置message提示信息，complexValid与方法名对应\r\n");
      out.write("                   return false;\r\n");
      out.write("               }\r\n");
      out.write("               else {\r\n");
      out.write("                   return true;\r\n");
      out.write("               }\r\n");
      out.write("           }\r\n");
      out.write("       },\r\n");
      out.write("    \tmessage : \"\"\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function submitLoginForm(){\r\n");
      out.write("  $('#login_form').form('submit',{\r\n");
      out.write("    onSubmit:function(){\r\n");
      out.write("      return $(this).form('enableValidation').form('validate');\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function clearForm(){\r\n");
      out.write("  $('#login_form').form('clear');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
